server:
  port: 6456


spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    poolSize: 100
    max-active: 50
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 40
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update